language: cpp
compiler:
  - gcc
  - clang
  - g++
install:
    sudo apt-get install libcurl4-openssl-dev
before_script:
    - cd ../
    - git clone git://github.com/allenbo/common.git
    - git clone git://github.com/allenbo/JConer.git
    - cd JConer && cp -R ../common/include/common include && make
    - cd ../libgdrive && mkdir lib
    - cp -R ../JConer/include/jconer include && cp ../JConer/libjconer.a lib/
    - cp -R ../common/include/common include
script: make
